name: Go

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -cover -covermode=atomic -coverprofile=coverage.txt ./...
    
    - name: Publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
          bash <(curl -s https://codecov.io/bash)
